---
- name: Aprovisionar VM con seguridad SSH
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
    ssh_public_key_path: "{{ lookup('env','HOME') }}/.ssh/dftd.pub"
  tasks:
    - import_tasks: proyecto_seguridad/tasks/user_and_group.yml 
    - import_tasks: proyecto_ssh_seguridad/tasks/authorized_keys.yml
    - import_tasks: proyecto_ssh_seguridad/tasks/two_factor.yml
    - import_tasks: proyecto_seguridad/tasks/pam_pwquality.yml

  handlers:
    - import_tasks: proyecto_ssh_seguridad/handlers/restart_ssh.yml
